//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public byte Month { get; set; }
        public short Year { get; set; }
        public decimal SalaryAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
